# Generated by Django 2.1 on 2022-12-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('account', models.CharField(max_length=64, verbose_name='账号')),
                ('note', models.CharField(max_length=64, verbose_name='备注')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('u_age', models.IntegerField(verbose_name='出生年月')),
                ('role', models.CharField(choices=[(1, '超级管理员'), (2, '网管'), (3, '会员')], max_length=16, verbose_name='角色')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
            ],
        ),
    ]
